markdown:         kramdown
permalink:        /posts/:title/
url:              https://chris.beams.io
port:             7200
livereload:       true
repository:       cbeams/chris.beams.io
gems:
  - jekyll-sitemap
include:
  - _redirects
exclude:
  - CNAME
  - Gemfile
  - README.md
