markdown:         redcarpet
permalink:        /writing/:title
title:            Chris Beams
url:              http://chris.beams.io
author:
  name:           Chris Beams
  email:          chris@beams.io
