# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        /writing/:title

# Setup
title:            Chris Beams
tagline:
url:              http://chris.beams.io
baseurl:          /
author:
  name:           Chris Beams
  url:            http://chris.beams.io
  email:          chris@beams.io
