markdown:         redcarpet
permalink:        /:categories/:title
title:            Chris Beams
url:              http://chris.beams.io
feedurl:          http://feed.chris.beams.io
author:
  name:           Chris Beams
  email:          chris@beams.io
