markdown:         kramdown
permalink:        /posts/:title/
url:              https://chris.beams.io
port:             7200
livereload:       true
gems:
  - jekyll-sitemap
exclude:
  - CNAME
  - Gemfile
  - README.md
